stages:
  - build
  - test
  - cleanup
  - deploy


build_job:
  stage: build
  script:
    - ci/nginx_build

test_job:
  stage: test
  script:
    - ci/nginx_test

cleanup:
  stage: cleanup
  script:
    - docker rm -f $(docker ps -aq)


deploy_job:
  stage: deploy
  script:
    - git push --mirror https://$GITHUB_TOKEN@github.com/Evild67/docker-alpine-nginx.git
