stages:
  - build
  - test
  - cleanup
  - deploy


build_job:
  stage: build
  script:
    - ci/nginx_build

test_job:
  stage: test
  script:
    - ci/nginx_test

cleanup:
  stage: cleanup
  script:
    - ci_nginx_cleanup
  when: always

deploy_job:
  stage: deploy
  script:
    - ci/nginx_deploy
