stages:
  - build
  - test
  - cleanup
  - tweet
  - deploy

build_job:
  stage: build
  script:
    - ci/nginx_build

test_job:
  stage: test
  script:
    - ci/nginx_test

cleanup:
  stage: cleanup
  script:
    - ci/nginx_cleanup
  when: always

tweet_job:
  stage: tweet
  only:
    - tags
    - triggers
    - master
  script:
    - ci/nginx_tweet

deploy_job:
  stage: deploy
  only:
    - tags
    - triggers
    - master
  script:
    - ci/nginx_deploy
