#!/bin/sh

set -e

if [ "$NIGHTLY_BUILD" ]; then

  docker run -p 5000:80 -d --name nginx-nightly-openssl evild/alpine-nginx:nightly-openssl
  docker ps | grep nginx-nightly-openssl
  sleep 10
  curl -I 127.0.0.1:5000

  docker run -p 5001:80 -d --name nginx-nightly-libressl evild/alpine-nginx:nightly-libressl
  docker ps | grep nginx-nightly-libressl
  sleep 10
  curl -I 127.0.0.1:5001

else

  docker run -p 5000:80 -d --name nginx-mainline-openssl evild/alpine-nginx:mainline-openssl
  docker ps | grep nginx-mainline-openssl
  sleep 10
  curl -I 127.0.0.1:5000

  docker run -p 5001:80 -d --name nginx-mainline-libressl evild/alpine-nginx:mainline-libressl
  docker ps | grep nginx-mainline-libressl
  sleep 10
  curl -I 127.0.0.1:5001

  docker run -p 5002:80 -d --name nginx-stable evild/alpine-nginx:stable
  docker ps | grep nginx-stable
  sleep 10
  curl -I 127.0.0.1:5002

fi
