#!/bin/sh

set -e

docker --version

if [ "$NIGHTLY_BUILD" ]; then

docker run -p 5000:80 -d --name nginx-nightly-openssl evild/alpine-nginx:nightly-openssl
docker ps | grep nginx-nightly-openssl
curl -I 127.0.0.1:5000

docker run -p 5001:80 -d --name nginx-nightly-libressl evild/alpine-nginx:nightly-libressl
docker ps | grep nginx-nightly-libressl
curl -I 127.0.0.1:5001

else

  docker run -p 5000:80 -d --name nginx-mainline-openssl evild/alpine-nginx:mainline-openssl
  docker ps | grep nginx-mainline-openssl
  curl -I 127.0.0.1:5000

  docker run -p 5001:80 -d --name nginx-mainline-libressl evild/alpine-nginx:mainline-libressl
  docker ps | grep nginx-mainline-libressl
  curl -I 127.0.0.1:5001

  docker run -p 5002:80 -d --name nginx-stable evild/alpine-nginx:stable
  docker ps | grep nginx-stable
  curl -I 127.0.0.1:5002

fi
